#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
  username: myblog
  password: <%= ENV['MYBLOG_DATABASE_PASSWORD'] %>
